// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// clfft_test
void clfft_test(SEXP ptrA_);
RcppExport SEXP gpuRclfft_clfft_test(SEXP ptrA_SEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptrA_(ptrA_SEXP);
    clfft_test(ptrA_);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"gpuRclfft_clfft_test", (DL_FUNC) &gpuRclfft_clfft_test, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_gpuRclfft(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
